//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro
    {
        public int CodLivro { get; set; }
        public string Titulo { get; set; }
        public string Autor { get; set; }
        public string Lancamento { get; set; }
        public string Editora { get; set; }
        public int Pag { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public string Genero { get; set; }
    }
}
